uploadPath: c:/mnt/
server:
  port: 8081
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-bp11dok2aa3314h5hfo.mysql.rds.aliyuncs.com/ssm_hq?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: chenhongjian
    password: chj123456
  freemarker:
    prefer-file-system-access: false
  redis:
    host: 127.0.0.1
    password: '@after'
feign:
  hystrix:
    enabled: true
eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    service-url:
#      defaultZone: http://192.168.1.37:8761/eureka #,http://localhost:8762/eureka
      defaultZone: http://test:123456@47.111.232.105:8761/eureka/